// Generated by scripts/chatpets-sprites.mjs from the walk-*.png strips here.
// Don't edit by hand: add or replace a cat with `npm run sprites -- <sheet> <name>`.
//
// Each strip is four cells of w×h in a row: right-1, right-2, left-1, left-2.

import plain from "./walk-plain.png";
import pumpkin from "./walk-pumpkin.png";
import sleepy from "./walk-sleepy.png";
import tongue from "./walk-tongue.png";
import witch from "./walk-witch.png";

/** An ordinary cat's height in these cells; the page scales so this is the pet size. */
export const CAT_H = 150;

export const WALKERS: { src: string; w: number; h: number }[] = [
  { src: plain.src, w: 204, h: 150 },
  { src: pumpkin.src, w: 240, h: 151 },
  { src: sleepy.src, w: 204, h: 145 },
  { src: tongue.src, w: 212, h: 153 },
  { src: witch.src, w: 210, h: 162 },
];
