// Turn a walking-pet sheet into a chat pets sprite strip.
//
//   npm run sprites -- path/to/sheet.png <set>/<name>
//
// e.g. `cats/bell` adds a cat to the set the cats' streamers use, and
// `special/whale` makes a sprite that only a chatter named in
// app/chatpets/pets.ts gets. Which streamer gets which set is decided there.
//
// The sheet is a 2×2 grid on a transparent background: the top row walks
// right (two frames), the bottom row walks left (two frames). The output is
// app/chatpets/sprites/walk/<set>/<name>.png, one row of four equal cells in
// the order right-1, right-2, left-1, left-2, and app/chatpets/sprites/walk/
// index.ts is rewritten to list every strip in every set, so the new one is
// picked up on the next build. Running it again with the same name replaces it.
//
// Two options, for sheets that don't come out that way:
//
//   --mirror           every frame faces right: walk right with the top row,
//                      and left with the same two frames flipped. The bottom
//                      row is ignored.
//   --bg black|white   the background is a solid colour rather than
//                      transparent. Only the colour connected to the sheet's
//                      edge is cleared, so the character's own blacks or
//                      whites survive.
//
// How a sheet is cut is in lib/spritesheet.ts, shared with the studio, where
// sprites can also be uploaded without a rebuild. This script is for the ones
// built into the app.

import sharp from "sharp";
import { mkdirSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
// The cutting itself is shared with the studio's upload (lib/spritesheet.ts),
// which is why this runs with --experimental-strip-types.
import { BUILT_IN_SCALE, CAT_H, clearBackground, findFrames, layoutStrip } from "../lib/spritesheet.ts";

const OUT = join(dirname(fileURLToPath(import.meta.url)), "..", "app", "chatpets", "sprites", "walk");

// A set is named like a Twitch login (a streamer's own set is usually named
// after them), a sprite like a file.
const SET = /^[a-z0-9_]{1,25}$/;
const NAME = /^[a-z0-9-]{1,30}$/;

const args = process.argv.slice(2);
const MIRROR = args.includes("--mirror");
const bgAt = args.indexOf("--bg");
const BG = bgAt >= 0 ? args[bgAt + 1] : "transparent";
const [sheet, rawId] = args.filter((a, i) => !a.startsWith("--") && !(bgAt >= 0 && i === bgAt + 1));
const [set, name] = String(rawId ?? "").toLowerCase().split("/");
if (!sheet || !SET.test(set ?? "") || !NAME.test(name ?? "") || !["transparent", "black", "white"].includes(BG)) {
  console.error(
    "usage: npm run sprites -- <sheet.png|webp> <set>/<name> [--mirror] [--bg black|white]   e.g. cats/bell, special/whale",
  );
  process.exit(1);
}

const { data, info } = await sharp(sheet).ensureAlpha().raw().toBuffer({ resolveWithObject: true });
const W = info.width;
const H = info.height;
clearBackground(data, W, H, BG);
const { frames, warnings } = findFrames(data, W, H, MIRROR);
for (const w of warnings) console.warn(`warning: ${w}`);
const strip = layoutStrip(frames, BUILT_IN_SCALE, MIRROR);
const cellW = strip.cellW;
const CELL_H = strip.cellH;

/** The sheet as it now stands (background cleared, if it was asked for). */
const source = () => sharp(data, { raw: { width: W, height: H, channels: 4 } });

const cells = await Promise.all(
  strip.cells.map(async (c) => {
    // Extracted to a buffer first: sharp applies flop before extract within
    // one pipeline, which would flip the whole sheet and cut the wrong frame.
    const cut = await source().extract(c.from).png().toBuffer();
    let img = sharp(cut).resize(c.width, c.height, { kernel: "lanczos3" });
    if (c.flip) img = img.flop();
    return { input: await img.png().toBuffer(), left: c.left, top: c.top };
  }),
);

mkdirSync(join(OUT, set), { recursive: true });
const file = `${set}/${name}.png`;
await sharp({ create: { width: cellW * 4, height: CELL_H, channels: 4, background: { r: 0, g: 0, b: 0, alpha: 0 } } })
  .composite(cells)
  .png({ compressionLevel: 9, palette: true, quality: 90, effort: 10 })
  .toFile(join(OUT, file));
console.log(`wrote app/chatpets/sprites/walk/${file} (${cellW}×${CELL_H} per frame)`);

// ---- the list the page imports ---------------------------------------------

const sets = readdirSync(OUT).filter((d) => SET.test(d) && statSync(join(OUT, d)).isDirectory()).sort();
const entries = [];
for (const d of sets) {
  for (const f of readdirSync(join(OUT, d)).filter((f) => /^[a-z0-9-]+\.png$/.test(f)).sort()) {
    const m = await sharp(join(OUT, d, f)).metadata();
    const n = f.slice(0, -4);
    entries.push({ set: d, id: `${d}/${n}`, file: `./${d}/${f}`, ident: `${d}_${n}`.replace(/[^a-z0-9]+(.)/g, (_, c) => c.toUpperCase()), w: m.width / 4, h: m.height });
  }
}
const ts = `// Generated by scripts/chatpets-sprites.mjs from the strips in the folders here.
// Don't edit by hand: add or replace one with \`npm run sprites -- <sheet> <set>/<name>\`.
// Which streamer gets which set, and who gets a sprite of their own, is in
// app/chatpets/pets.ts.
//
// Each strip is four cells of w×h in a row: right-1, right-2, left-1, left-2.

${entries.map((e) => `import ${e.ident} from "${e.file}";`).join("\n")}

export type Walker = { id: string; src: string; w: number; h: number };

/** An ordinary cat's height in these cells; the page scales so this is the pet size. */
export const CAT_H = ${CAT_H};

export const WALK_SETS: Record<string, Walker[]> = {
${sets
  .map((d) => `  ${d}: [\n${entries.filter((e) => e.set === d).map((e) => `    { id: "${e.id}", src: ${e.ident}.src, w: ${e.w}, h: ${e.h} },`).join("\n")}\n  ],`)
  .join("\n")}
};
`;
writeFileSync(join(OUT, "index.ts"), ts);
console.log(`index.ts: ${sets.map((d) => `${d} (${entries.filter((e) => e.set === d).length})`).join(", ")}`);
