// Turn a walking-cat sheet into a chat pets sprite strip.
//
//   npm run sprites -- path/to/sheet.png <name>
//
// The sheet is a 2×2 grid on a transparent background: the top row walks
// right (two frames), the bottom row walks left (two frames). The output is
// app/chatpets/sprites/walk-<name>.png, one row of four equal cells in the
// order right-1, right-2, left-1, left-2, and app/chatpets/sprites/walkers.ts
// is rewritten to list every walk-*.png there, so the new cat is picked up on
// the next build. Running it again with the same name replaces that cat.
//
// Each frame is cut out by its own bounding box, then placed so the feet sit on
// the bottom edge and the nose stays put between frames (right-aligned for the
// right-facing pair, left-aligned for the other) — otherwise the cat's head
// jumps back and forth as the frames alternate, which reads as jitter rather
// than walking.

import sharp from "sharp";
import { readdirSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const OUT = join(dirname(fileURLToPath(import.meta.url)), "..", "app", "chatpets", "sprites");
// Every sheet is stored at the same scale, rather than every cat at the same
// height: otherwise a cat in a tall hat is drawn smaller than one without.
// The sheets are ~420px-tall cats on a 1536×1024 canvas, so this keeps a cat
// about 150px tall — twice the biggest size anyone is likely to use on a
// 1080p canvas, so they stay sharp when the browser scales them down.
const SCALE = 1 / 2.8;
// A plain cat's height at that scale. The page sizes pets by this, so the
// "pet size" setting is how tall an ordinary cat is, hat or no hat.
const CAT_H = 150;
// Clear space either side of each frame. Neighbouring frames in the strip
// would otherwise touch nose to nose, and a browser scaling the strip down
// blends a sliver of the next frame into this one's edge.
const PAD = 4;
// Faint edge pixels below this alpha don't count towards a frame's box.
const SOLID = 64;

const [sheet, rawName] = process.argv.slice(2);
const name = String(rawName ?? "").toLowerCase();
if (!sheet || !/^[a-z0-9-]{1,30}$/.test(name)) {
  console.error("usage: npm run sprites -- <sheet.png|webp> <name>   (name: a-z, 0-9, -)");
  process.exit(1);
}

const { data, info } = await sharp(sheet).ensureAlpha().raw().toBuffer({ resolveWithObject: true });
const W = info.width;
const H = info.height;
const alpha = (x, y) => data[(y * W + x) * 4 + 3];

/** Bounding box of the solid pixels inside one quadrant. */
function box(x0, y0, x1, y1) {
  let l = x1, t = y1, r = -1, b = -1;
  for (let y = y0; y < y1; y++)
    for (let x = x0; x < x1; x++)
      if (alpha(x, y) >= SOLID) {
        if (x < l) l = x;
        if (x > r) r = x;
        if (y < t) t = y;
        if (y > b) b = y;
      }
  if (r < 0) throw new Error(`no cat found in the quadrant at ${x0},${y0}`);
  // A frame that reaches the dividing line has probably been cut in half.
  if (l === x0 || t === y0 || r === x1 - 1 || b === y1 - 1) {
    console.warn(`warning: the frame at ${x0},${y0} touches the quadrant edge; check the output`);
  }
  return { left: l, top: t, width: r - l + 1, height: b - t + 1 };
}

const mx = Math.floor(W / 2);
const my = Math.floor(H / 2);
const frames = [
  box(0, 0, mx, my), // right 1
  box(mx, 0, W, my), // right 2
  box(0, my, mx, H), // left 1
  box(mx, my, W, H), // left 2
];

const srcW = Math.max(...frames.map((f) => f.width));
const srcH = Math.max(...frames.map((f) => f.height));
const scale = SCALE;
const cellW = Math.round(srcW * scale) + PAD * 2;
const CELL_H = Math.round(srcH * scale);

const cells = await Promise.all(
  frames.map(async (f, i) => {
    const w = Math.max(1, Math.round(f.width * scale));
    const h = Math.max(1, Math.round(f.height * scale));
    const input = await sharp(sheet).extract(f).resize(w, h, { kernel: "lanczos3" }).png().toBuffer();
    const facingRight = i < 2;
    return { input, left: i * cellW + (facingRight ? cellW - PAD - w : PAD), top: CELL_H - h };
  }),
);

const file = `walk-${name}.png`;
await sharp({ create: { width: cellW * 4, height: CELL_H, channels: 4, background: { r: 0, g: 0, b: 0, alpha: 0 } } })
  .composite(cells)
  .png({ compressionLevel: 9, palette: true, quality: 90, effort: 10 })
  .toFile(join(OUT, file));
console.log(`wrote app/chatpets/sprites/${file} (${cellW}×${CELL_H} per frame)`);

// ---- the list the page imports ---------------------------------------------

const strips = readdirSync(OUT).filter((f) => /^walk-[a-z0-9-]+\.png$/.test(f)).sort();
const entries = [];
for (const f of strips) {
  const m = await sharp(join(OUT, f)).metadata();
  entries.push({ f, id: f.slice(5, -4).replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase()), w: m.width / 4, h: m.height });
}
const ts = `// Generated by scripts/chatpets-sprites.mjs from the walk-*.png strips here.
// Don't edit by hand: add or replace a cat with \`npm run sprites -- <sheet> <name>\`.
//
// Each strip is four cells of w×h in a row: right-1, right-2, left-1, left-2.

${entries.map((e) => `import ${e.id} from "./${e.f}";`).join("\n")}

/** An ordinary cat's height in these cells; the page scales so this is the pet size. */
export const CAT_H = ${CAT_H};

export const WALKERS: { src: string; w: number; h: number }[] = [
${entries.map((e) => `  { src: ${e.id}.src, w: ${e.w}, h: ${e.h} },`).join("\n")}
];
`;
writeFileSync(join(OUT, "walkers.ts"), ts);
console.log(`walkers.ts lists ${entries.length} cat${entries.length === 1 ? "" : "s"}: ${strips.join(", ")}`);
