-- v2: switch et_flags from nickname-based to steam_id-based with rank system.
-- Run once: psql "$DATABASE_URL" -f db/migrations/002_et_v2.sql

DROP TABLE IF EXISTS et_flags;

-- Cache FACEIT nickname → Steam ID lookups to avoid hitting the FACEIT API
-- on every page load. 24-hour TTL enforced by the application layer.
CREATE TABLE IF NOT EXISTS et_player_cache (
  nickname          TEXT PRIMARY KEY,   -- lowercase FACEIT nickname
  faceit_player_id  TEXT NOT NULL,
  steam_id          TEXT NOT NULL,
  cached_at         TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS et_player_cache_steam_id_idx ON et_player_cache (steam_id);

-- Community griefer flags, keyed by Steam ID so nickname changes don't break tracking.
-- rank: S (worst) → A → B → C → D → F (least bad).
CREATE TABLE IF NOT EXISTS et_flags (
  id            BIGSERIAL PRIMARY KEY,
  steam_id      TEXT NOT NULL,
  display_name  TEXT,                   -- FACEIT nickname at time of flagging, for display only
  rank          TEXT NOT NULL CHECK (rank IN ('S','A','B','C','D','F')),
  comment       TEXT NOT NULL,
  reporter_id   TEXT NOT NULL,          -- anonymous UUID generated by the extension on install
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (reporter_id, steam_id)
);

CREATE INDEX IF NOT EXISTS et_flags_steam_id_idx ON et_flags (steam_id);
