// Generated by scripts/chatpets-sprites.mjs from the strips in the folders here.
// Don't edit by hand: add or replace one with `npm run sprites -- <sheet> <set>/<name>`.
// Which streamer gets which set, and who gets a sprite of their own, is in
// app/chatpets/pets.ts.
//
// Each strip is four cells of w×h in a row: right-1, right-2, left-1, left-2.

import catsBell from "./cats/bell.png";
import catsPlain from "./cats/plain.png";
import catsPumpkin from "./cats/pumpkin.png";
import catsSatchel from "./cats/satchel.png";
import catsSleepy from "./cats/sleepy.png";
import catsTongue from "./cats/tongue.png";
import catsWitch from "./cats/witch.png";
import juntellaBell from "./juntella/bell.png";
import juntellaSleepy from "./juntella/sleepy.png";
import juntellaTabby from "./juntella/tabby.png";
import specialVera from "./special/vera.png";
import specialWhale from "./special/whale.png";

export type Walker = { id: string; src: string; w: number; h: number };

/** An ordinary cat's height in these cells; the page scales so this is the pet size. */
export const CAT_H = 150;

export const WALK_SETS: Record<string, Walker[]> = {
  cats: [
    { id: "cats/bell", src: catsBell.src, w: 216, h: 156 },
    { id: "cats/plain", src: catsPlain.src, w: 204, h: 150 },
    { id: "cats/pumpkin", src: catsPumpkin.src, w: 240, h: 151 },
    { id: "cats/satchel", src: catsSatchel.src, w: 216, h: 156 },
    { id: "cats/sleepy", src: catsSleepy.src, w: 204, h: 145 },
    { id: "cats/tongue", src: catsTongue.src, w: 212, h: 153 },
    { id: "cats/witch", src: catsWitch.src, w: 210, h: 162 },
  ],
  juntella: [
    { id: "juntella/bell", src: juntellaBell.src, w: 229, h: 160 },
    { id: "juntella/sleepy", src: juntellaSleepy.src, w: 240, h: 163 },
    { id: "juntella/tabby", src: juntellaTabby.src, w: 231, h: 160 },
  ],
  special: [
    { id: "special/vera", src: specialVera.src, w: 252, h: 165 },
    { id: "special/whale", src: specialWhale.src, w: 264, h: 143 },
  ],
};
